# Generated by Django 3.1.2 on 2020-10-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceguard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(db_column='Address', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, db_column='Age', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(db_column='Job', default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, db_column='Sex', max_length=10, null=True),
        ),
    ]
